# メニュー設定ファイル - 管理メニュー
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- module: AdminProject
- module: AdminAccount
- separator: yes
- module: AdminLog
- module: DevelopTableReport
- separator: yes
- title: ログアウト
  module: Default
  action: Logout