# メニュー設定ファイル - ユーザー向けメニュー
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

- module: UserProject
- module: UserAccount
- separator: yes
- title: ログアウト
  module: Default
  action: Logout