# アプリケーション定数設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: コモンズファイル管理システム
    en: COMMONS File Management System
  ver: 2.0.0-dev

author:
  name: コモンズ株式会社
  email: info@commons.co.jp

crypt:
  salt: TEBE1CXJ7V7OZ6DC

languages:
  - ja
  - en

