# アプリケーション定数設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

app:
  name:
    ja: COMMONS TABLE
    en: COMMONS TABLE
  ver: 2.1.0b5 (2012-04-09)

author:
  name: コモンズ株式会社
  name_en: COMMONS CO., LTD
  email: info@commons.co.jp

crypt:
  engine: cbc
  salt: TEBE1CXJ7V7OZ6DC

module:
  secure:
    module: Default
    action: Login

mail:
  sender: smtp

image:
  thumbnail:
    bgcolor: white

languages:
  - ja
  - en

