# ホスト別設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://cfms.glaive.local/
root_url_https: http://cfms.glaive.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  networks:
    - 192.168.102.0/24

pdo:
  default:
    dsn: mysql:host=127.0.0.1;dbname=cfms
    uid: root
    password:
