<?php
/* --------------------------------------------------------------------------

	[CFMS] ŠÇ—‰æ–Ê ’è”Ý’è

	2004.06.30	01	cms

-------------------------------------------------------------------------- */



// include

		require_once("../_inc/xdef.inc");
		require_once("xfcn.admin.inc");



// application

		define("_APP_NAME_",			_ADMIN_NAME_);
		define("_APP_NAME_S_",		_ADMIN_NAME_S_);
		define("_APP_URL_",				_ADMIN_URL_);
		define("_APP_VER_",				_ADMIN_VER_);



?>