# ディレクトリレイアウト設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

account:
  parent: var
delivery:
  parent: var
idea:
  parent: var
local_images:
  parent: www
  name: images
project:
  parent: var
themes:
  parent: webapp
  suffix: .css