# JavaScriptセット設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

user:
  files:
    - prototype
    - scriptaculous/effects
    - glider
    - mjl
    - carrot
    - application
