# スタイルセット設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>

cfms:
  files:
    - cfms
    - protocalendar
    - prototabs
    - lightbox
    - glider
    - color_picker
    - application
