# スタイルセット設定ファイル
#
# @package jp.co.commons.cfms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

cfms:
  files:
    - cfms
    - protocalendar
    - prototabs
    - lightbox
    - color_picker
    - application
