<?php
define("DEBUG", true);

define("DB_HOST", "127.0.0.1");
define("DB_USER", "root");
define("DB_PWD", "");
define("DB_NAME", "cfms1");

define("ROOT_URL", "http://cfms.torkan.local/");
define("ROOT_PATH", "/home/pooza/Sites/cfms.torkan.local/www/");

define("MTA_HOST", "localhost");
define("MTA_TZ", "+0900");
define("ADMIN_EMAIL", "webmaster@torkan.local");

define("MAX_FILE_SIZE", 60); // ファイルサイズの上限
define("NEW_DATE", 2); // New!を表示する日数
define("STORAGE_PATH", "/Users/pooza/Sites/cfms.torkan.local/var/cfms1/"); // ファイル格納場所

$arrayBlankClass = array("JPG", "PNG", "GIF", "TXT", "PDF");
$arrayThumbClass = array("JPG", "GIF");
